<a href="https://colab.research.google.com/github/ThamirisAdriano/BlockchainApp/blob/main/Self_attention.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###Vamos implementar um exemplo simples de Self-Attention em Python.




A função softmax é usada para converter as pontuações em uma distribuição de probabilidade.


In [ ]:
import numpy as np

def softmax(x):
    return np.exp(x) / np.sum(np.exp(x), axis=-1, keepdims=True)


In [ ]:
def self_attention(Q, K, V):
    # Calcula as pontuações de atenção
    scores = np.dot(Q, K.T)
    # Aplica softmax às pontuações
    attention_weights = softmax(scores)
    # Calcula a saída ponderada
    output = np.dot(attention_weights, V)
    return output, attention_weights




scores: Calcula as pontuações de atenção como o produto escalar de Q e K.

attention_weights: Converte as pontuações em pesos de atenção usando softmax.

output: Calcula a saída ponderada multiplicando os pesos de atenção pelos valores (V).

In [ ]:
# Exemplo de dados de entrada (Q, K, V são iguais para self-attention)
X = np.array([
    [1, 0, 1],  # Palavra 1
    [0, 2, 0],  # Palavra 2
    [1, 1, 1]   # Palavra 3
])

# Aplicando Self-Attention
output, attention_weights = self_attention(X, X, X)



Matriz de entrada onde cada linha representa a representação vetorial de uma palavra na sequência.


In [ ]:
print("Entrada (X):")
print(X)
print("\nPesos de Atenção:")
print(attention_weights)
print("\nSaída com Self-Attention Aplicada:")
print(output)

Entrada (X):
[[1 0 1]
 [0 2 0]
 [1 1 1]]

Pesos de Atenção:
[[0.46831053 0.06337894 0.46831053]
 [0.01587624 0.86681333 0.11731043]
 [0.21194156 0.21194156 0.57611688]]

Saída com Self-Attention Aplicada:
[[0.93662106 0.59506841 0.93662106]
 [0.13318667 1.85093709 0.13318667]
 [0.78805844 1.         0.78805844]]
